### ISSUE TITLE
KeyError 'directory'

### ISSUE THREAD

**Issue by adybbroe** [pytroll/trollmoves#74]
The latest trollmoves release broke my code that worked with the previous master:
```
msb:
  host: ''  
  dispatch_configs:
    - topics:
        - /VIIRS/L2/Fires/PP
      conditions:
        - product: afimg
          type: GEOJSON-filtered
          platform_name: [NOAA-20, Suomi-NPP]
          format: [GEOJSON, geojson]
      filepattern: '{product}_{start_time:%Y%m%d_%H%M%S}.{format}'
      directory: /satmsb
```
